<?php

namespace Kenzal\MetalsApi\Symbols;

use Kenzal\MetalsApi\Contracts\SymbolInterface;
use Kenzal\MetalsApi\Traits\SymbolFunctions;

enum Currency: string implements SymbolInterface
{
    use SymbolFunctions;

    case ADA = 'ADA'; // Cardano
    case AED = 'AED'; // United Arab Emirates Dirham
    case AFN = 'AFN'; // Afghan Afghani
    case ALL = 'ALL'; // Albanian Lek
    case AMD = 'AMD'; // Armenian Dram
    case ANG = 'ANG'; // Netherlands Antillean Gulden
    case AOA = 'AOA'; // Angolan Kwanza
    case ARS = 'ARS'; // Argentine Peso
    case AUD = 'AUD'; // Australian Dollar
    case AWG = 'AWG'; // Aruban Florin
    case AZN = 'AZN'; // Azerbaijani Manat
    case BAM = 'BAM'; // Bosnia and Herzegovina Convertible Mark
    case BBD = 'BBD'; // Barbadian Dollar
    case BCH = 'BCH'; // Bitcoin Cash
    case BDT = 'BDT'; // Bangladeshi Taka
    case BGN = 'BGN'; // Bulgarian Lev
    case BHD = 'BHD'; // Bahraini Dinar
    case BIF = 'BIF'; // Burundian Franc
    case BMD = 'BMD'; // Bermudian Dollar
    case BND = 'BND'; // Brunei Dollar
    case BOB = 'BOB'; // Bolivian Boliviano
    case BRL = 'BRL'; // Brazilian Real
    case BSD = 'BSD'; // Bahamian Dollar
    case BTC = 'BTC'; // Bitcoin
    case BTN = 'BTN'; // Bhutanese Ngultrum
    case BWP = 'BWP'; // Botswana Pula
    case BYN = 'BYN'; // Belarusian Ruble
    case BYR = 'BYR'; // Belarusian Ruble
    case BZD = 'BZD'; // Belize Dollar
    case CAD = 'CAD'; // Canadian Dollar
    case CDF = 'CDF'; // Congolese Franc
    case CHF = 'CHF'; // Swiss Franc
    case CLF = 'CLF'; // Unidad de Fomento
    case CLP = 'CLP'; // Chilean Peso
    case CNH = 'CNH'; // Chinese Renminbi Yuan Offshore
    case CNY = 'CNY'; // Chinese Renminbi Yuan
    case COP = 'COP'; // Colombian Peso
    case CRC = 'CRC'; // Costa Rican Colón
    case CUC = 'CUC'; // Cuban Convertible Peso
    case CVE = 'CVE'; // Cape Verdean Escudo
    case CZK = 'CZK'; // Czech Koruna
    case DJF = 'DJF'; // Djiboutian Franc
    case DKK = 'DKK'; // Danish Krone
    case DOP = 'DOP'; // Dominican Peso
    case DZD = 'DZD'; // Algerian Dinar
    case EEK = 'EEK'; // Estonian Kroon
    case EGP = 'EGP'; // Egyptian Pound
    case ERN = 'ERN'; // Eritrean Nakfa
    case ETB = 'ETB'; // Ethiopian Birr
    case ETH = 'ETH'; // Ethereum
    case EUR = 'EUR'; // Euro
    case FJD = 'FJD'; // Fijian Dollar
    case FKP = 'FKP'; // Falkland Pound
    case GBP = 'GBP'; // British Pound
    case GEL = 'GEL'; // Georgian Lari
    case GGP = 'GGP'; // Guernsey Pound
    case GHS = 'GHS'; // Ghanaian Cedi
    case GIP = 'GIP'; // Gibraltar Pound
    case GMD = 'GMD'; // Gambian Dalasi
    case GNF = 'GNF'; // Guinean Franc
    case GTQ = 'GTQ'; // Guatemalan Quetzal
    case GYD = 'GYD'; // Guyanese Dollar
    case HKD = 'HKD'; // Hong Kong Dollar
    case HNL = 'HNL'; // Honduran Lempira
    case HRK = 'HRK'; // Croatian Kuna
    case HTG = 'HTG'; // Haitian Gourde
    case HUF = 'HUF'; // Hungarian Forint
    case IDR = 'IDR'; // Indonesian Rupiah
    case ILS = 'ILS'; // Israeli New Sheqel
    case IMP = 'IMP'; // Isle of Man Pound
    case INR = 'INR'; // Indian Rupee
    case IQD = 'IQD'; // Iraqi Dinar
    case JEP = 'JEP'; // Jersey Pound
    case JMD = 'JMD'; // Jamaican Dollar
    case JOD = 'JOD'; // Jordanian Dinar
    case JPY = 'JPY'; // Japanese Yen
    case KES = 'KES'; // Kenyan Shilling
    case KGS = 'KGS'; // Kyrgyzstani Som
    case KHR = 'KHR'; // Cambodian Riel
    case KMF = 'KMF'; // Comorian Franc
    case KRW = 'KRW'; // South Korean Won
    case KWD = 'KWD'; // Kuwaiti Dinar
    case KYD = 'KYD'; // Cayman Islands Dollar
    case KZT = 'KZT'; // Kazakhstani Tenge
    case LAK = 'LAK'; // Lao Kip
    case LBP = 'LBP'; // Lebanese Pound
    case LINK = 'LINK'; // Chainlink
    case LKR = 'LKR'; // Sri Lankan Rupee
    case LRD = 'LRD'; // Liberian Dollar
    case LSL = 'LSL'; // Lesotho Loti
    case LTC = 'LTC'; // Litecoin
    case LTL = 'LTL'; // Lithuanian Litas
    case LVL = 'LVL'; // Latvian Lats
    case LYD = 'LYD'; // Libyan Dinar
    case MAD = 'MAD'; // Moroccan Dirham
    case MDL = 'MDL'; // Moldovan Leu
    case MGA = 'MGA'; // Malagasy Ariary
    case MKD = 'MKD'; // Macedonian Denar
    case MMK = 'MMK'; // Myanmar Kyat
    case MNT = 'MNT'; // Mongolian Tögrög
    case MOP = 'MOP'; // Macanese Pataca
    case MRO = 'MRO'; // Mauritanian Ouguiya
    case MTL = 'MTL'; // Maltese Lira
    case MUR = 'MUR'; // Mauritian Rupee
    case MVR = 'MVR'; // Maldivian Rufiyaa
    case MWK = 'MWK'; // Malawian Kwacha
    case MXN = 'MXN'; // Mexican Peso
    case MYR = 'MYR'; // Malaysian Ringgit
    case MZN = 'MZN'; // Mozambican Metical
    case NAD = 'NAD'; // Namibian Dollar
    case NGN = 'NGN'; // Nigerian Naira
    case NIO = 'NIO'; // Nicaraguan Córdoba
    case NOK = 'NOK'; // Norwegian Krone
    case NPR = 'NPR'; // Nepalese Rupee
    case NZD = 'NZD'; // New Zealand Dollar
    case OMR = 'OMR'; // Omani Rial
    case PAB = 'PAB'; // Panamanian Balboa
    case PEN = 'PEN'; // Peruvian Sol
    case PGK = 'PGK'; // Papua New Guinean Kina
    case PHP = 'PHP'; // Philippine Peso
    case PKR = 'PKR'; // Pakistani Rupee
    case PLN = 'PLN'; // Polish Złoty
    case PYG = 'PYG'; // Paraguayan Guaraní
    case QAR = 'QAR'; // Qatari Riyal
    case RON = 'RON'; // Romanian Leu
    case RSD = 'RSD'; // Serbian Dinar
    case RUB = 'RUB'; // Russian Ruble
    case RWF = 'RWF'; // Rwandan Franc
    case SAR = 'SAR'; // Saudi Riyal
    case SBD = 'SBD'; // Solomon Islands Dollar
    case SCR = 'SCR'; // Seychellois Rupee
    case SEK = 'SEK'; // Swedish Krona
    case SGD = 'SGD'; // Singapore Dollar
    case SHP = 'SHP'; // Saint Helenian Pound
    case SLL = 'SLL'; // Sierra Leonean Leone
    case SOS = 'SOS'; // Somali Shilling
    case SRD = 'SRD'; // Surinamese Dollar
    case SSP = 'SSP'; // South Sudanese Pound
    case STD = 'STD'; // São Tomé and Príncipe Dobra
    case SVC = 'SVC'; // Salvadoran Colón
    case SZL = 'SZL'; // Swazi Lilangeni
    case THB = 'THB'; // Thai Baht
    case TJS = 'TJS'; // Tajikistani Somoni
    case TMT = 'TMT'; // Turkmenistani Manat
    case TND = 'TND'; // Tunisian Dinar
    case TOP = 'TOP'; // Tongan Paʻanga
    case TRY = 'TRY'; // Turkish Lira
    case TTD = 'TTD'; // Trinidad and Tobago Dollar
    case TWD = 'TWD'; // New Taiwan Dollar
    case TZS = 'TZS'; // Tanzanian Shilling
    case UAH = 'UAH'; // Ukrainian Hryvnia
    case UGX = 'UGX'; // Ugandan Shilling
    case UNI = 'UNI'; // Uniswap
    case USD = 'USD'; // United States Dollar
    case UYU = 'UYU'; // Uruguayan Peso
    case UZS = 'UZS'; // Uzbekistan Som
    case VEF = 'VEF'; // Venezuelan Bolívar
    case VES = 'VES'; // Venezuelan Bolívar Soberano
    case VND = 'VND'; // Vietnamese Đồng
    case VUV = 'VUV'; // Vanuatu Vatu
    case WST = 'WST'; // Samoan Tala
    case XAF = 'XAF'; // Central African Cfa Franc
    case XCD = 'XCD'; // East Caribbean Dollar
    case XDR = 'XDR'; // Special Drawing Rights
    case XLM = 'XLM'; // Stellar
    case XOF = 'XOF'; // West African Cfa Franc
    case XPF = 'XPF'; // Cfp Franc
    case XRP = 'XRP'; // Ripple
    case XRP2 = 'XRP2'; // Ripple
    case YER = 'YER'; // Yemeni Rial
    case ZAR = 'ZAR'; // South African Rand
    case ZMK = 'ZMK'; // Zambian Kwacha
    case ZMW = 'ZMW'; // Zambian Kwacha
    case ZWL = 'ZWL'; // Zimbabwean Dollar

    public function getDescription(): string
    {
        return match ($this) {
            Currency::ADA => 'Cardano',
            Currency::AED => 'United Arab Emirates Dirham',
            Currency::AFN => 'Afghan Afghani',
            Currency::ALL => 'Albanian Lek',
            Currency::AMD => 'Armenian Dram',
            Currency::ANG => 'Netherlands Antillean Gulden',
            Currency::AOA => 'Angolan Kwanza',
            Currency::ARS => 'Argentine Peso',
            Currency::AUD => 'Australian Dollar',
            Currency::AWG => 'Aruban Florin',
            Currency::AZN => 'Azerbaijani Manat',
            Currency::BAM => 'Bosnia and Herzegovina Convertible Mark',
            Currency::BBD => 'Barbadian Dollar',
            Currency::BCH => 'Bitcoin Cash',
            Currency::BDT => 'Bangladeshi Taka',
            Currency::BGN => 'Bulgarian Lev',
            Currency::BHD => 'Bahraini Dinar',
            Currency::BIF => 'Burundian Franc',
            Currency::BMD => 'Bermudian Dollar',
            Currency::BND => 'Brunei Dollar',
            Currency::BOB => 'Bolivian Boliviano',
            Currency::BRL => 'Brazilian Real',
            Currency::BSD => 'Bahamian Dollar',
            Currency::BTC => 'Bitcoin',
            Currency::BTN => 'Bhutanese Ngultrum',
            Currency::BWP => 'Botswana Pula',
            Currency::BYN => 'Belarusian Ruble',
            Currency::BYR => 'Belarusian Ruble',
            Currency::BZD => 'Belize Dollar',
            Currency::CAD => 'Canadian Dollar',
            Currency::CDF => 'Congolese Franc',
            Currency::CHF => 'Swiss Franc',
            Currency::CLF => 'Unidad de Fomento',
            Currency::CLP => 'Chilean Peso',
            Currency::CNH => 'Chinese Renminbi Yuan Offshore',
            Currency::CNY => 'Chinese Renminbi Yuan',
            Currency::COP => 'Colombian Peso',
            Currency::CRC => 'Costa Rican Colón',
            Currency::CUC => 'Cuban Convertible Peso',
            Currency::CVE => 'Cape Verdean Escudo',
            Currency::CZK => 'Czech Koruna',
            Currency::DJF => 'Djiboutian Franc',
            Currency::DKK => 'Danish Krone',
            Currency::DOP => 'Dominican Peso',
            Currency::DZD => 'Algerian Dinar',
            Currency::EEK => 'Estonian Kroon',
            Currency::EGP => 'Egyptian Pound',
            Currency::ERN => 'Eritrean Nakfa',
            Currency::ETB => 'Ethiopian Birr',
            Currency::ETH => 'Ethereum',
            Currency::EUR => 'Euro',
            Currency::FJD => 'Fijian Dollar',
            Currency::FKP => 'Falkland Pound',
            Currency::GBP => 'British Pound',
            Currency::GEL => 'Georgian Lari',
            Currency::GGP => 'Guernsey Pound',
            Currency::GHS => 'Ghanaian Cedi',
            Currency::GIP => 'Gibraltar Pound',
            Currency::GMD => 'Gambian Dalasi',
            Currency::GNF => 'Guinean Franc',
            Currency::GTQ => 'Guatemalan Quetzal',
            Currency::GYD => 'Guyanese Dollar',
            Currency::HKD => 'Hong Kong Dollar',
            Currency::HNL => 'Honduran Lempira',
            Currency::HRK => 'Croatian Kuna',
            Currency::HTG => 'Haitian Gourde',
            Currency::HUF => 'Hungarian Forint',
            Currency::IDR => 'Indonesian Rupiah',
            Currency::ILS => 'Israeli New Sheqel',
            Currency::IMP => 'Isle of Man Pound',
            Currency::INR => 'Indian Rupee',
            Currency::IQD => 'Iraqi Dinar',
            Currency::JEP => 'Jersey Pound',
            Currency::JMD => 'Jamaican Dollar',
            Currency::JOD => 'Jordanian Dinar',
            Currency::JPY => 'Japanese Yen',
            Currency::KES => 'Kenyan Shilling',
            Currency::KGS => 'Kyrgyzstani Som',
            Currency::KHR => 'Cambodian Riel',
            Currency::KMF => 'Comorian Franc',
            Currency::KRW => 'South Korean Won',
            Currency::KWD => 'Kuwaiti Dinar',
            Currency::KYD => 'Cayman Islands Dollar',
            Currency::KZT => 'Kazakhstani Tenge',
            Currency::LAK => 'Lao Kip',
            Currency::LBP => 'Lebanese Pound',
            Currency::LINK => 'Chainlink',
            Currency::LKR => 'Sri Lankan Rupee',
            Currency::LRD => 'Liberian Dollar',
            Currency::LSL => 'Lesotho Loti',
            Currency::LTC => 'Litecoin',
            Currency::LTL => 'Lithuanian Litas',
            Currency::LVL => 'Latvian Lats',
            Currency::LYD => 'Libyan Dinar',
            Currency::MAD => 'Moroccan Dirham',
            Currency::MDL => 'Moldovan Leu',
            Currency::MGA => 'Malagasy Ariary',
            Currency::MKD => 'Macedonian Denar',
            Currency::MMK => 'Myanmar Kyat',
            Currency::MNT => 'Mongolian Tögrög',
            Currency::MOP => 'Macanese Pataca',
            Currency::MRO => 'Mauritanian Ouguiya',
            Currency::MTL => 'Maltese Lira',
            Currency::MUR => 'Mauritian Rupee',
            Currency::MVR => 'Maldivian Rufiyaa',
            Currency::MWK => 'Malawian Kwacha',
            Currency::MXN => 'Mexican Peso',
            Currency::MYR => 'Malaysian Ringgit',
            Currency::MZN => 'Mozambican Metical',
            Currency::NAD => 'Namibian Dollar',
            Currency::NGN => 'Nigerian Naira',
            Currency::NIO => 'Nicaraguan Córdoba',
            Currency::NOK => 'Norwegian Krone',
            Currency::NPR => 'Nepalese Rupee',
            Currency::NZD => 'New Zealand Dollar',
            Currency::OMR => 'Omani Rial',
            Currency::PAB => 'Panamanian Balboa',
            Currency::PEN => 'Peruvian Sol',
            Currency::PGK => 'Papua New Guinean Kina',
            Currency::PHP => 'Philippine Peso',
            Currency::PKR => 'Pakistani Rupee',
            Currency::PLN => 'Polish Złoty',
            Currency::PYG => 'Paraguayan Guaraní',
            Currency::QAR => 'Qatari Riyal',
            Currency::RON => 'Romanian Leu',
            Currency::RSD => 'Serbian Dinar',
            Currency::RUB => 'Russian Ruble',
            Currency::RWF => 'Rwandan Franc',
            Currency::SAR => 'Saudi Riyal',
            Currency::SBD => 'Solomon Islands Dollar',
            Currency::SCR => 'Seychellois Rupee',
            Currency::SEK => 'Swedish Krona',
            Currency::SGD => 'Singapore Dollar',
            Currency::SHP => 'Saint Helenian Pound',
            Currency::SLL => 'Sierra Leonean Leone',
            Currency::SOS => 'Somali Shilling',
            Currency::SRD => 'Surinamese Dollar',
            Currency::SSP => 'South Sudanese Pound',
            Currency::STD => 'São Tomé and Príncipe Dobra',
            Currency::SVC => 'Salvadoran Colón',
            Currency::SZL => 'Swazi Lilangeni',
            Currency::THB => 'Thai Baht',
            Currency::TJS => 'Tajikistani Somoni',
            Currency::TMT => 'Turkmenistani Manat',
            Currency::TND => 'Tunisian Dinar',
            Currency::TOP => 'Tongan Paʻanga',
            Currency::TRY => 'Turkish Lira',
            Currency::TTD => 'Trinidad and Tobago Dollar',
            Currency::TWD => 'New Taiwan Dollar',
            Currency::TZS => 'Tanzanian Shilling',
            Currency::UAH => 'Ukrainian Hryvnia',
            Currency::UGX => 'Ugandan Shilling',
            Currency::UNI => 'Uniswap',
            Currency::USD => 'United States Dollar',
            Currency::UYU => 'Uruguayan Peso',
            Currency::UZS => 'Uzbekistan Som',
            Currency::VEF => 'Venezuelan Bolívar',
            Currency::VES => 'Venezuelan Bolívar Soberano',
            Currency::VND => 'Vietnamese Đồng',
            Currency::VUV => 'Vanuatu Vatu',
            Currency::WST => 'Samoan Tala',
            Currency::XAF => 'Central African Cfa Franc',
            Currency::XCD => 'East Caribbean Dollar',
            Currency::XDR => 'Special Drawing Rights',
            Currency::XLM => 'Stellar',
            Currency::XOF => 'West African Cfa Franc',
            Currency::XPF => 'Cfp Franc',
            Currency::XRP => 'Ripple',
            Currency::XRP2 => 'Ripple',
            Currency::YER => 'Yemeni Rial',
            Currency::ZAR => 'South African Rand',
            Currency::ZMK => 'Zambian Kwacha',
            Currency::ZMW => 'Zambian Kwacha',
            Currency::ZWL => 'Zimbabwean Dollar',
        };
    }
}
